-- Para usar una base de datos especifica
use sakila;
-- Para mostrar tablas de dicha BD
SHOW TABLES;
-- Para ver los detalles de dicha BD
DESCRIBE CITY;
-- Ver valores de dicha tabla
SELECT * FROM CITY;
-- CREAR UNA TABLA DESDE UNA TABLA EXISTENTE
CREATE TABLE KOI SELECT CITY_ID, PHONE, DISTRICT, LOCATION FROM ADDRESS;
SELECT * FROM KOI;
-- ELIMINAR UNA COLUMNA DE UNA TABLA
ALTER TABLE KOI 
DROP COLUMN DISTRICT;
SELECT * FROM KOI;

-- AÑADIR UNA COLUMNA A UNA TABLA

ALTER TABLE KOI 
ADD COLUMN NUEVO_DISTRITO VARCHAR(20);

SELECT * FROM KOI;

-- ELIMINAR TABLAS EN SQL
DROP TABLE koi;
-- TRUNCAR TABLAS 
TRUNCATE TABLE KOI;

create database prueba;
use prueba;



