CREATE DATABASE Vet;
USE Vet;
CREATE TABLE MASCOTAS(
	ID INT NOT NULL,
    NOMBRE VARCHAR(20),
    ID_DUEÑO INT NOT NULL,
    SERVICIO VARCHAR(20),
    PRIMARY KEY (ID)
    -- FOREIGN KEY (ID_DUEÑO) REFERENCES PERSONAS(ID)
);

CREATE TABLE PERSONAS(
	ID INT NOT NULL,
    NOMBRE VARCHAR(20),
    APELLIDO VARCHAR(20),
    COD_ZIP VARCHAR(20),
    TLF VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID)
    -- FOREIGN KEY (COD_ZIP) REFERENCES DIRECCIONES(ZIP)
);
CREATE TABLE DIRECCIONES(
	ZIP VARCHAR(20),
    NOMBRE_ZONA VARCHAR(20)
    -- RUTA VARCHAR(20)
);

ALTER TABLE MASCOTAS
ADD constraint FK_PERSONASID
FOREIGN KEY (ID_DUEÑO) REFERENCES PERSONAS(ID);

ALTER TABLE DIRECCIONES
ADD PRIMARY KEY (ZIP);

ALTER TABLE PERSONAS
ADD constraint FK_DIRECZIP
FOREIGN KEY (COD_ZIP) REFERENCES DIRECCIONES(ZIP);

ALTER TABLE PERSONAS
ADD COLUMN EMAIL VARCHAR(40);

ALTER TABLE PERSONAS 
ADD CONSTRAINT u_email UNIQUE (EMAIL);

ALTER TABLE MASCOTAS 
CHANGE NOMBRE PRIMER_NOMBRE VARCHAR(20);

ALTER TABLE DIRECCIONES
ADD COLUMN RUTA VARCHAR(20);

ALTER TABLE DIRECCIONES
MODIFY RUTA CHAR(12);

DESC PERSONAS;
