CREATE DATABASE BODEGA;

USE BODEGA;

CREATE TABLE PRODUCTOS(
	ID INT NOT NULL PRIMARY KEY auto_increment,
    Nombre varchar (28),
    Precio FLOAT,
    Proovedor VARCHAR(28)
);

DESC PRODUCTOS;

-- INSERTAR DATOS

INSERT INTO PRODUCTOS (NOMBRE, PRECIO, PROOVEDOR)
	VALUES
    ("CAFE",3.99, "LUCKY_LUCAS_CA"),
    ("HARINA DE TRIGO",1.75, "EL_HORNO_DE_ATENAS"),
    ("GASEOSA",1.50,"YORGELIS_2007");
    
SELECT * FROM PRODUCTOS;


INSERT INTO PRODUCTOS (NOMBRE, PRECIO, PROOVEDOR)
	VALUES
    ("MANTEQUILLA",2,"MILANAT"),
    ("GALLETAS DE VAINILLA",2,"DELICIAS_XIOMARA"),
    ("ENCENDEDORES",0.9,"LUCKY_LUCAS_CA"),
    ("LECHE",1.75,"MILANAT"),
    ("GOMITAS",0.9,"CHUCHU_ELDUCE");
    