UPDATE PRODUCTOS
SET PROOVEDOR = "MOLTISANTI_CA"
WHERE ID = 1; -- SOBRE QUE PK

SELECT * FROM PRODUCTOS;

-- PARA ACTUALIZAR MAS DE UNA COLUMNA A LA VEZ

SET SQL_SAFE_UPDATES = 0;

UPDATE PRODUCTOS
SET PRECIO = 0.9, PROOVEDOR = "MILANAT" 
WHERE NOMBRE = "GASEOSA";

-- ACTUALIZAR DOS FILAS A LA VEZ

UPDATE PRODUCTOS
SET PROOVEDOR = "MOLTISANTI_CA"
WHERE PROOVEDOR = "LUCKY_LUCAS_CA";